const $=s=>document.querySelector(s);const routes=[{name:'亞洲—北歐',via:'經蘇伊士',level:'高',node:'曼德海峽',alt:'繞行好望角',color:'red',path:[[121,25],[104,1],[80,5],[43,12],[33,30],[15,36],[-5,36],[4,52]],note:'航道風險升高，建議比較蘇伊士與好望角方案的航程及成本。'},{name:'亞洲—北歐',via:'繞好望角',level:'中',node:'好望角',alt:'經蘇伊士',color:'amber',path:[[121,25],[104,1],[65,-15],[18,-34],[-8,0],[-12,30],[4,52]],note:'避開紅海航段，但需要評估較長航程帶來的燃油與交期影響。'},{name:'亞洲—中東',via:'經荷莫茲',level:'危急',node:'荷莫茲海峽',alt:'調整掛靠港',color:'red',path:[[121,25],[104,1],[80,5],[58,20],[56,26],[50,28]],note:'關鍵航道存在高度不確定性，需評估替代港口與陸運銜接。'},{name:'亞洲—美西',via:'跨太平洋',level:'低',node:'太平洋航段',alt:'調整出發時段',color:'cyan',path:[[121,25],[150,35],[180,42],[-150,40],[-118,34]],note:'航道風險較低，持續監控目的港與燃油成本。'},{name:'亞洲—美東',via:'經巴拿馬',level:'低',node:'巴拿馬運河',alt:'替代轉運配置',color:'cyan',path:[[121,25],[155,15],[-170,10],[-120,5],[-80,9],[-74,40]],note:'持續追蹤運河通行條件及目的港等待時間。'},{name:'亞洲—南美',via:'南美西岸',level:'中',node:'目的港與內陸',alt:'調整目的港',color:'amber',path:[[121,25],[160,5],[-160,-10],[-100,-15],[-77,-12]],note:'整合港口與內陸資訊，評估目的港及交付風險。'}];
const events=[
{type:'航道安全',title:'中東航道需要評估備援',desc:'亞洲—中東 · 經荷莫茲',route:2,status:'優先評估',impact:'關鍵航道通行受限，需比較替代掛靠與陸運銜接。',evidence:'應交叉比對通行量、航安通告與事件時間；預測市場僅作為輔助訊號。',action:'比較備援方案'},
{type:'航道安全',title:'紅海航道通行受影響',desc:'亞洲—北歐 · 經蘇伊士',route:0,status:'優先評估',impact:'原航線途經曼德海峽，需評估繞行好望角對交期與成本的影響。',evidence:'應確認異常通行量與航安通告是否對應同一航段及期間，避免僅憑單一數值判定。',action:'比較好望角方案'},
{type:'燃油成本',title:'繞行方案需要重算成本',desc:'亞洲—北歐 · 繞好望角',route:1,status:'成本評估',impact:'繞行可能增加航程；燃油價格與價差變化會影響替代方案的成本。',evidence:'合併觀察原油價格、OVX 與燃油裂解價差，評估繞行成本。',action:'比較航程與成本'},
{type:'政策與關稅',title:'提前出貨需求待確認',desc:'亞洲—美西 · 延伸關注美東',route:3,status:'待確認',impact:'需先確認政策變更與進口量是否支持提前拉貨，再決定船位配置。',evidence:'比對政策生效日期、進口量與貨流變化，評估運力配置。',action:'查看方案'},
{type:'港口與內陸',title:'目的港與內陸交付風險',desc:'亞洲—南美 · 港口與內陸銜接',route:5,status:'持續關注',impact:'追蹤掛靠港與內陸路徑，評估交付中斷風險。',evidence:'綜合港口作業、罷工、治安、施工與通關資訊。',action:'查看替代港方案'},
{type:'國家風險',title:'市場布局需比對國家評級',desc:'南美市場 · 區域航線布局',route:5,status:'持續關注',impact:'市場進入與運力布局需依國家及航運產業風險分別評估。',evidence:'依 CRR 與 SRR 評級，比較目的市場與航運產業風險。',action:'查看配置方案'}];
const routeIssues=['航道通行受影響','需重算繞行成本','需要評估備援','提前出貨待確認','目的港交付評估','港口與內陸持續關注'];
let activeIssue=null,networkVisible=true;let selected=0,step=4,filter='全部',timer=null;
function selectRoute(i,issue=null){selected=i;activeIssue=issue||events.find(e=>e.route===i)||{type:'港口與內陸',title:'目的港交付評估',status:'持續關注',impact:'需確認目的港與運河通行條件，才能評估交付時效。',evidence:'比對目的港等待時間、船期與運河通行條件。',action:'查看方案'};const r=routes[i];$('#routeTitle').innerHTML=r.name+' <span>'+r.via+'</span>';$('#routeBadge').textContent=activeIssue.status;$('#routeBadge').className='badge '+r.color;$('#routeNode').textContent=r.node;$('#routeRisk').textContent=activeIssue.status;$('#routeRisk').className=r.color;$('#routeAlt').innerHTML=r.alt+' <span>↗</span>';$('#routeNote').textContent=r.note;$('#issueType').textContent=activeIssue.type;$('#issueTitle').textContent=activeIssue.title;$('#issueImpact').textContent=activeIssue.impact;$('#evidenceText').textContent=activeIssue.evidence;$('#compare').innerHTML=activeIssue.action+' <span>→</span>';document.querySelectorAll('.route-card').forEach((b,k)=>b.classList.toggle('active',k===i));lon=[50,30,58,165,210,235][i];lat=[24,-10,23,25,20,0][i];$('#monitorRisk').textContent=activeIssue.status;$('#monitorRisk').className=r.color;$('#monitorNode').textContent=r.node;setPanel('route');updateCharts();draw();}
$('#routeCards').innerHTML=routes.map((r,i)=>`<button class="route-card ${i===0?'active':''}" data-route="${i}"><h4>${r.name}</h4><small>${r.via}</small><span class="route-problem ${r.color}">${routeIssues[i]}</span></button>`).join('');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>selectRoute(+b.dataset.route));
function showEvents(f){filter=f;const list=events.filter(e=>f==='全部'||e.type===f);$('#eventCount').textContent=list.length+' 則';$('#eventList').innerHTML=list.map(e=>`<button class="attention-card" data-event="${events.indexOf(e)}"><div class="attention-meta"><span>${e.type}</span><small>${e.status}</small></div><h3>${e.title}</h3><p>${e.desc}</p><span class="attention-link">查看影響與依據 →</span></button>`).join('');document.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>{const e=events[+b.dataset.event];selectRoute(e.route,e)});document.querySelectorAll('.feed-filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>showEvents(b.dataset.filter));showEvents('全部');
const dates=['2026.06.08','2026.07.08','2026.08.08','2026.09.08','2026.10.08'];function setTime(n){step=n;$('#time').value=n;$('#dateTop').textContent=$('#dateBottom').textContent=dates[n];$('#overall').textContent=['持續監測','局部升溫','風險升高','高度關注','高度關注'][n];$('#affected').innerHTML=[1,2,3,4,4][n]+'<span>/ 6</span>';updateCharts();draw()}function stop(){clearInterval(timer);timer=null;$('#play').textContent='▶';$('#play').setAttribute('aria-label','播放情境回放')}$('#time').oninput=e=>{stop();setTime(+e.target.value)};$('#play').onclick=()=>{if(timer){stop();return}if(step===4)setTime(0);$('#play').textContent='Ⅱ';$('#play').setAttribute('aria-label','暫停情境回放');timer=setInterval(()=>{if(step>=4)stop();else setTime(step+1)},1400)};$('#now').onclick=()=>{stop();setTime(4)};stop();
function setPanel(name){$('#eventsPanel').hidden=name!=='events';$('#routePanel').hidden=name!=='route';$('#panelTitle').textContent=name==='events'?'需關注事項':'影響分析';$('.right-column').classList.add('expanded');$('.panel-scroll').scrollTop=0;}
$('#panelCollapse').onclick=()=>$('.right-column').classList.toggle('expanded');$('#backToIssues').onclick=()=>{setPanel('events');lon=75;lat=20;draw()};$('#reportSelected').onclick=()=>report();$('#replayToggle').onclick=()=>{const open=$('#replayControls').hidden;$('#replayControls').hidden=!open;$('#replayToggle').setAttribute('aria-expanded',String(open));$('.workspace').classList.toggle('replaying',open);if(!open)stop();};
function compare(){const r=routes[selected];$('#comparisonContent').innerHTML=`<div class="comparison-grid"><article><span class="eyebrow">原方案</span><h3>${r.name} · ${r.via}</h3><dl><dt>模擬航程</dt><dd>28 天</dd><dt>成本指數</dt><dd>100</dd><dt>主要風險</dt><dd>${r.node}</dd><dt>風險等級</dt><dd>${r.level}</dd></dl></article><article><span class="eyebrow">備援方案</span><h3>${r.alt}</h3><dl><dt>模擬航程</dt><dd>36 天 / +8 天</dd><dt>成本指數</dt><dd>118 / +18%</dd><dt>主要取捨</dt><dd>交期與成本增加</dd><dt>待驗證項目</dt><dd>運力、港口與海象</dd></dl></article></div>`;$('#comparison').showModal()}$('#compare').onclick=compare;$('.close').onclick=()=>$('#comparison').close();$('#comparison').onclick=e=>{if(e.target===$('#comparison'))$('#comparison').close()};
function report(){const r=routes[selected];const report=`<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><title>陽明航線風險分析 · 展示報告</title><style>body{font:16px system-ui;max-width:900px;margin:60px auto;padding:25px;color:#173445;line-height:1.9}h1{font-size:32px}small{color:#607582}section{padding:20px 0;border-bottom:1px solid #ddd}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:12px;border-bottom:1px solid #ddd}.tag{background:#fff0e5;padding:12px}button{padding:10px}@media print{button{display:none}}</style><small>YANG MING / MARITIME INTELLIGENCE</small><h1>航線風險情境分析報告</h1><p class="tag">展示原型：所有風險、事件與數值均為模擬，非實際預測或航行指令。</p><section><h2>${r.name} · ${r.via}</h2><p>情境日期：${dates[step]}<br>匯出時間：${new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}（台北）</p><p>${r.note}</p></section><section><h2>風險摘要</h2><p>主要節點：${r.node} ／ 模擬風險：${r.level}</p></section><section><h2>方案比較</h2><table><tr><th>項目</th><th>原方案</th><th>${r.alt}</th></tr><tr><td>模擬航程</td><td>28 天</td><td>36 天</td></tr><tr><td>成本指數</td><td>100</td><td>118</td></tr></table></section><section><h2>分析條件與限制</h2><p>固定示範情境，未串接 AIS、船舶性能、氣象海象、港口、燃油或實際船期資料。替代方案尚未經可行性驗證，時間與成本僅用於展示比較方式。</p></section><p><small>本報告為產出當下的靜態快照，可離線開啟。</small></p><button onclick="window.print()">列印報告</button></html>`;const url=URL.createObjectURL(new Blob([report],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='YM-航線分析-'+dates[step]+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#toast').textContent='已下載 HTML 展示報告，可離線開啟';$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3000)}$('#export').onclick=$('#report2').onclick=report;
// Orthographic globe. Local Natural Earth geometry; no map service required.
const canvas=$('#globe'),ctx=canvas.getContext('2d');let W,H,R,cx,cy,lon=75,lat=20,drag=null,zoom=1.15,labelsVisible=true;const rad=Math.PI/180;
function project(a,b){let la=b*rad,lo=(a-lon)*rad,ph=lat*rad;let z=Math.sin(ph)*Math.sin(la)+Math.cos(ph)*Math.cos(la)*Math.cos(lo);return [cx+R*Math.cos(la)*Math.sin(lo),cy-R*(Math.cos(ph)*Math.sin(la)-Math.sin(ph)*Math.cos(la)*Math.cos(lo)),z]}
function line(points,color,width=1,dash=[]){ctx.beginPath();let on=false;for(const p of points){const q=project(p[0],p[1]);if(q[2]>.015){if(on)ctx.lineTo(q[0],q[1]);else ctx.moveTo(q[0],q[1]);on=true}else on=false}ctx.shadowColor=color;ctx.shadowBlur=width>2?10:0;ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.shadowBlur=0;ctx.setLineDash([])}
function interpolate(a,b){let d=b[0]-a[0];if(d>180)d-=360;if(d< -180)d+=360;return Array.from({length:31},(_,i)=>[a[0]+d*i/30,a[1]+(b[1]-a[1])*i/30])}
function pathline(path,color,width,dash){let pts=[];for(let i=1;i<path.length;i++)pts.push(...interpolate(path[i-1],path[i]));line(pts,color,width,dash)}
function draw(){if(!W)return;ctx.clearRect(0,0,W,H);let glow=ctx.createRadialGradient(cx,cy,R*.8,cx,cy,R*1.2);glow.addColorStop(0,'#417cd400');glow.addColorStop(.55,'#3d81e619');glow.addColorStop(1,'#417cd400');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);let sea=ctx.createRadialGradient(cx-R*.35,cy-R*.45,0,cx,cy,R);sea.addColorStop(0,'#162c4e');sea.addColorStop(.65,'#102c3c');sea.addColorStop(1,'#071723');ctx.fillStyle=sea;ctx.fill();ctx.save();ctx.clip();paintTexture();
if(labelsVisible){for(const f of window.COUNTRIES){const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;for(const poly of polys)line(poly[0],'#94befc77',.8);}const occupied=[];ctx.font='500 11px "Noto Sans TC",sans-serif';ctx.textAlign='center';for(const f of [...window.COUNTRIES].sort((a,b)=>a.rank-b.rank)){if(f.rank>(zoom>1.5?6:3))continue;const q=project(f.x,f.y);if(q[2]<.35||q[0]<30||q[0]>W-30||q[1]<30||q[1]>H-35)continue;const w=ctx.measureText(f.name).width+14;if(occupied.some(p=>Math.abs(p[0]-q[0])<(p[2]+w)/2&&Math.abs(p[1]-q[1])<21))continue;occupied.push([q[0],q[1],w]);ctx.lineWidth=3;ctx.strokeStyle='#07121bcc';ctx.strokeText(f.name,q[0],q[1]);ctx.fillStyle='#f1efe3';ctx.fillText(f.name,q[0],q[1]);}ctx.textAlign='left';}
if(networkVisible)routes.forEach((r,i)=>pathline(r.path,i===selected?'#8bb8fc':'#5188da66',i===selected?2.6:1.1,i===1?[4,4]:[]));if(networkVisible&&selected===0)pathline(routes[1].path,'#dab77b77',1,[4,5]);
const locations=[{p:[121,25],n:'高雄',c:'#7eacf2'},{p:[104,1],n:'新加坡',c:'#7eacf2'},{p:[4,52],n:'鹿特丹',c:'#7eacf2'},{p:[56,26],n:'荷莫茲海峽',c:'#ff8581',risk:true},{p:[43,12],n:'曼德海峽',c:'#ecad77',risk:true},{p:[18,-34],n:'好望角',c:'#91a6c5'},{p:[-118,34],n:'洛杉磯',c:'#7eacf2'},{p:[-80,9],n:'巴拿馬運河',c:'#7eacf2'}];locations.forEach((l,i)=>{let q=project(...l.p);if(q[2]<.08)return;ctx.shadowColor=l.c;ctx.shadowBlur=l.risk?14:7;ctx.beginPath();ctx.arc(q[0],q[1],l.risk?4:2.5,0,Math.PI*2);ctx.fillStyle=l.c;ctx.fill();ctx.shadowBlur=0;if(l.risk){ctx.beginPath();ctx.arc(q[0],q[1],10+step,0,Math.PI*2);ctx.strokeStyle=l.c+'55';ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(q[0],q[1],22+step*2,0,Math.PI*2);ctx.strokeStyle=l.c+'19';ctx.stroke()}ctx.font='10px "Noto Sans TC", sans-serif';ctx.fillStyle=l.risk?'#f8c4b4':'#b5c3d9';ctx.fillText(l.n,q[0]+10,q[1]+(i===3?-12:17));});let shade=ctx.createLinearGradient(cx-R,cy-R,cx+R,cy+R);shade.addColorStop(0,'#06101c00');shade.addColorStop(.6,'#06101c00');shade.addColorStop(1,'#01071099');ctx.fillStyle=shade;ctx.fillRect(0,0,W,H);ctx.restore();ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.strokeStyle='#86aee94f';ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(cx,cy,R+6,-Math.PI*.97,-Math.PI*.05);ctx.strokeStyle='#8bb5f532';ctx.lineWidth=.5;ctx.stroke();}
const textureCanvas=document.createElement('canvas'),textureCtx=textureCanvas.getContext('2d',{willReadFrequently:true}),surface=document.createElement('canvas'),surfaceCtx=surface.getContext('2d');let texturePixels=null,tw=0,th=0,cachedKey='';const textureImage=new Image();textureImage.onload=()=>{tw=textureImage.width;th=textureImage.height;textureCanvas.width=tw;textureCanvas.height=th;textureCtx.drawImage(textureImage,0,0);texturePixels=textureCtx.getImageData(0,0,tw,th).data;draw();};textureImage.onerror=()=>{document.querySelector('.earth-credit').textContent='地表影像載入失敗';};textureImage.src=window.EARTH_TEXTURE;
function paintTexture(){if(!texturePixels)return;const resolution=drag?.6:Math.min(devicePixelRatio||1,1.4);const sw=Math.ceil(W*resolution),sh=Math.ceil(H*resolution);const key=[sw,sh,lon,lat,R].join(',');if(key!==cachedKey){surface.width=sw;surface.height=sh;const frame=surfaceCtx.createImageData(sw,sh),out=frame.data;const sp=Math.sin(lat*rad),cp=Math.cos(lat*rad);for(let y=0;y<sh;y++){const ny=(cy-y/resolution)/R;for(let x=0;x<sw;x++){const nx=(x/resolution-cx)/R,r2=nx*nx+ny*ny;if(r2>=1)continue;const z=Math.sqrt(1-r2),la=Math.asin(ny*cp+z*sp),lo=lon*rad+Math.atan2(nx,z*cp-ny*sp);const u=(((lo/(2*Math.PI)+.5)%1)+1)%1;const tx=Math.min(tw-1,Math.floor(u*tw)),ty=Math.min(th-1,Math.max(0,Math.floor((.5-la/Math.PI)*th))),source=(ty*tw+tx)*4,k=(y*sw+x)*4;const light=.48+.52*Math.max(0,-nx*.3+ny*.25+z*.9);out[k]=texturePixels[source]*light;out[k+1]=texturePixels[source+1]*light;out[k+2]=texturePixels[source+2]*light;out[k+3]=255;}}surfaceCtx.putImageData(frame,0,0);cachedKey=key;}ctx.drawImage(surface,0,0,W,H);}
function resize(){W=canvas.clientWidth;H=canvas.clientHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);R=Math.min(W*.43,H*.46)*zoom;cx=W/2;cy=H*.49;draw()}new ResizeObserver(resize).observe(canvas);canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY,lon,lat];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;lon=drag[2]-(e.clientX-drag[0])*.3;lat=Math.max(-60,Math.min(60,drag[3]+(e.clientY-drag[1])*.2));draw()};canvas.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag[0],e.clientY-drag[1])<6){const box=canvas.getBoundingClientRect(),x=e.clientX-box.left,y=e.clientY-box.top;for(const [a,b,i] of [[56,26,2],[43,12,0],[18,-34,1],[121,25,0],[104,1,0],[4,52,0],[-118,34,3],[-80,9,4]]){const q=project(a,b);if(q[2]>.08&&Math.hypot(q[0]-x,q[1]-y)<22){selectRoute(i);break;}}}drag=null;draw();};canvas.onpointercancel=()=>drag=null;$('#reset').onclick=()=>{lon=75;lat=20;zoom=1.15;resize()};

$('#networkToggle').onclick=()=>{networkVisible=!networkVisible;$('#networkToggle').setAttribute('aria-pressed',String(networkVisible));draw();};

function zoomBy(factor){zoom=Math.max(.85,Math.min(3,zoom*factor));resize();}$('#zoomIn').onclick=()=>zoomBy(1.2);$('#zoomOut').onclick=()=>zoomBy(1/1.2);$('#north').onclick=()=>{lat=20;draw()};canvas.addEventListener('wheel',e=>{e.preventDefault();zoomBy(e.deltaY<0?1.08:1/1.08)},{passive:false});$('#labelsToggle').onclick=()=>{labelsVisible=!labelsVisible;$('#labelsToggle').setAttribute('aria-pressed',String(labelsVisible));draw()};

const trafficSeries=[[100,94,91,86,79,75,72],[100,101,98,96,94,93,92],[100,93,76,61,45,31,28],[100,102,99,104,101,102,103],[100,98,100,96,95,98,97],[100,97,93,95,90,91,89]];
function miniChart(values,color,label,id){const min=Math.floor(Math.min(...values)/10)*10-10,max=Math.ceil(Math.max(...values)/10)*10+10;const x=i=>28+i*232/(values.length-1),y=v=>70-(v-min)/(max-min)*56;const pts=values.map((v,i)=>`${x(i)},${y(v)}`).join(' '),last=values.length-1;return `<svg viewBox="0 0 278 94" role="img" aria-label="${label}，${values.join('、')}"><defs><linearGradient id="${id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="${color}" stop-opacity=".3"/><stop offset="100%" stop-color="${color}" stop-opacity="0"/></linearGradient></defs>${[0,.5,1].map(t=>`<line x1="28" x2="260" y1="${14+t*56}" y2="${14+t*56}" stroke="#293445" stroke-dasharray="2 4"/><text x="1" y="${17+t*56}" fill="#667283" font-size="8">${Math.round(max-t*(max-min))}</text>`).join('')}<polygon points="28,70 ${pts} 260,70" fill="url(#${id})"/><polyline points="${pts}" fill="none" stroke="${color}" stroke-width="1.8" stroke-linejoin="round"/>${values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="${i===last?3:2}" fill="${color}"><title>第 ${i+1} 期：${v}</title></circle>`).join('')}<text x="28" y="88" fill="#788291" font-size="8">期初</text><text x="233" y="88" fill="#788291" font-size="8">本期</text></svg>`;}
function updateCharts(){const type=activeIssue?.type||'航道安全';const traffic=type==='航道安全'&&selected<3,fuel=type==='燃油成本';$('#trendData').hidden=!(traffic||fuel);$('#trendUnavailable').hidden=traffic||fuel;$('#trendUnavailable').textContent='綜合事件與相關航線，查看下方判讀依據。';$('#trendTitle').textContent=traffic?routes[selected].node+'通行趨勢':fuel?'原油與燃油價差':'綜合判讀';$('#chartExplanation').textContent=traffic?'通行指數，基準期＝100。':fuel?'藍線：原油；橙線：燃油價差。指數，基準期＝100。':'';if(traffic){const values=trafficSeries[selected].slice(0,step+3),last=values.at(-1),delta=last-values[0];$('#trendValue').textContent=last;$('#trendDelta').textContent=(delta>0?'+':'')+delta+'% 較期初';$('#trendDelta').className=delta<0?'red':'cyan';$('#trafficChart').innerHTML=miniChart(values,'#6195e4','通行指數','trafficFill');}else if(fuel){$('#trendValue').textContent='118.6';$('#trendDelta').textContent='價差指數';$('#trendDelta').className='amber';const crude=[100,102,101,100,99,100,100],spread=[100,103,108,106,113,115,118.6];const points=v=>v.map((n,i)=>`${28+i*232/6},${70-(n-90)/40*56}`).join(' ');$('#trafficChart').innerHTML=`<svg viewBox="0 0 278 94" role="img" aria-label="原油指數持平於100，燃油價差指數升至118.6">${[90,110,130].map(n=>`<text x="0" y="${73-(n-90)/40*56}" fill="#8296b1" font-size="8">${n}</text><line x1="28" x2="260" y1="${70-(n-90)/40*56}" y2="${70-(n-90)/40*56}" stroke="#293d59"/>`).join('')}<polyline points="${points(crude)}" stroke="#6195e4" fill="none" stroke-width="2"/><polyline points="${points(spread)}" stroke="#e4b66c" fill="none" stroke-width="2"/><text x="28" y="88" fill="#8296b1" font-size="8">期初</text><text x="239" y="88" fill="#8296b1" font-size="8">本期</text></svg>`;}}
updateCharts();
