/* YM information architecture and local prototype pages. No external data APIs. */
const PAGE_MAP={overview:['戰情總覽','掌握需要優先處理的事項'],safety:['航道安全','判讀航道訊號，評估主線與備援'],policy:['政策與關稅','從政策變化觀察貨流與出貨時點'],fuel:['燃油成本','一起觀察油價、波動率與裂解價差'],ports:['港口與內陸','辨識影響到港與內陸交付的中斷'],countries:['國家風險','比較國家與產業評級，支援市場布局'],routes:['航線分析','整合五類風險，再比較情境方案'],reports:['分析報告','選擇報告內容、預覽並匯出 HTML']};
const pageState={route:0,scenario:null,report:null};let currentPage='overview';
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prototypeNote='';
function panel(title,body,sub=''){return `<section class="page-card"><div class="page-card-head"><h2>${title}</h2>${sub?`<span>${sub}</span>`:''}</div>${body}</section>`}
function routeOptions(){return routes.map((r,i)=>`<option value="${i}" ${i===pageState.route?'selected':''}>${r.name} · ${r.via}</option>`).join('')}
function table(headers,rows){return `<div class="table-scroll"><table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function emptyData(text){return `<div class="data-empty"><p>${text}</p></div>`}
function nextRoute(i,label='分析相關航線'){return `<button class="page-button" data-open-route="${i}">${label} →</button>`}
function spark(values,label,color='#7baaff'){return miniChart(values,color,label,'page-'+Math.random().toString(36).slice(2))}
function sourceDetails(items){return ''}
function renderSafety(){return `<div class="page-toolbar"><label>關鍵航道<select id="waterway"><option value="0">曼德海峽</option><option value="2">荷莫茲海峽</option><option value="1">好望角</option></select></label><label>觀察區間<select id="safetyPeriod"><option value="7">近 7 期</option><option value="4">近 4 期</option></select></label><span class="toolbar-note">通行指數期初＝100</span></div><div class="page-grid"><div>${panel('航道通行趨勢','<div id="safetyChart"></div><p id="safetyReading" class="reading"></p>','量化訊號')}${panel('事件與預警時間軸',`<ol class="event-timeline"><li><small>2025 年 4 月</small><h3>區域擾動可能推升成本</h3><p>追蹤區域事件與成本變化。</p></li><li><small>2025 年 6 月</small><h3>商船與航道可能受報復性攻擊影響</h3><p>比對航安通告與商船通行狀況。</p></li><li><small>2026 年 3 月</small><h3>衝突對航道的影響具體化</h3><p>持續追蹤航道通行與區域事件。</p></li></ol>`)}</div><div>${panel('受影響航線','<div id="safetyRoutes"></div>')}${panel('事件市場預期',emptyData('綜合事件合約、市場機率與成交量，觀察市場預期。'),'Polymarket 輔助訊號')}${panel('應對方向','<ul class="plain-list"><li>主航線與備援方案一併比較。</li><li>衡量繞行的時間、燃油與營運影響。</li><li>觀察通行恢復條件，持續調整判斷。</li></ul>')}</div></div>${sourceDetails(['依原始簡報「航道安全」及「Polymarket」主題整理。','通行數列為固定模擬情境，未連接 AIS 或航安通告。','預警門檻、誤報率與回測方式尚待定義。'])}`}
function updateSafety(){const i=+$('#waterway').value,count=+$('#safetyPeriod').value,v=trafficSeries[i].slice(-count);$('#safetyChart').innerHTML=spark(v,'航道通行指數');$('#safetyReading').textContent=`本區間由 ${v[0]} 至 ${v.at(-1)}，變動 ${((v.at(-1)/v[0]-1)*100).toFixed(1)}%。`;$('#safetyRoutes').innerHTML=`<p class="reading">${routes[i].name} · ${routes[i].via}</p>${nextRoute(i)}`;bindRouteButtons();}
function renderPolicy(){return `<div class="page-toolbar"><label>貿易市場<select id="tradeMarket"><option>美國</option><option>歐洲</option></select></label><span class="toolbar-note">追蹤政策公告與需求訊號</span></div><div class="page-grid"><div>${panel('進口量與提前出貨訊號','<div id="tradeChart"></div><p id="tradeReading" class="reading"></p>','指數')}${panel('政策追蹤清單',table(['觀察項目','追蹤內容'],[['關稅調整','適用產品、地區、生效日' ],['貿易協定','談判狀態、正式公告' ],['替代樞紐','港口承載與貨流變化' ]]))}</div><div>${panel('判讀步驟','<ol class="plain-list"><li>確認公告與生效時間。</li><li>對照進口量及歷史同期。</li><li>跨市場比對，確認是否為提前拉貨。</li><li>再討論船位保留與加班船。</li></ol>')}${panel('相關航線','<div id="policyRoutes"></div>')}${panel('需求判斷',emptyData('進口量上升可能有多種原因；未比對政策與季節性前，不直接推薦增加運力。'))}</div></div>${sourceDetails(['依簡報「政策與關稅」整理。','進口量圖為視覺示例，沒有接入海關、港口或貿易政策資料。'])}`}
function updatePolicy(){const us=$('#tradeMarket').value==='美國';$('#tradeChart').innerHTML=spark(us?[100,108,123,118,112,106,103]:[100,99,103,105,104,108,109],'進口量指數');$('#tradeReading').textContent=us?'短期增量後回落，需判斷是否為提前拉貨。':'溫和增加，需比對市場與季節性，尚不能判斷異常。';$('#policyRoutes').innerHTML=us?nextRoute(3,'查看亞洲—美西')+' '+nextRoute(4,'查看亞洲—美東'):nextRoute(0,'查看亞洲—北歐');bindRouteButtons();}
function renderFuel(){return `<div class="page-grid"><div>${panel('原油與燃油裂解價差',`<div class="chart-legend"><span>● 原油指數</span><span class="amber">● 裂解價差指數</span></div><div class="wide-chart">${fuelGraph()}</div><p class="reading">原油相對持平，燃油裂解價差上升，關注燃油成本壓力。</p>`,'指數 · 期初＝100')}${panel('成本敏感度試算',`<form id="fuelCalc" class="form-grid"><label>每日耗油量（噸）<input name="burn" type="number" min="1" max="500" step="1" value="70" required></label><label>燃油價格（美元／噸）<input name="price" type="number" min="1" max="5000" value="600" required></label><label>航程天數<input name="days" type="number" min="1" max="100" value="28" required></label><label>價格變動（%）<input name="change" type="number" min="-90" max="200" value="10" required></label><button class="page-button" type="submit">計算燃油影響</button></form><div id="fuelResult" class="calc-result"></div><p class="micro-note">僅計燃油，未含港費、保險、租金、碳成本與天候因素。</p>`)}</div><div>${panel('原油波動率 OVX',emptyData('觀察原油市場波動率，評估市場不確定性的變化。'))}${panel('計算假設','<p class="reading">依耗油量、燃油價格與航程天數計算成本。</p>'+nextRoute(1,'前往備援航線試算'))}${panel('分析指標','<ul class="plain-list"><li>原油與船用燃油報價及其單位。</li><li>同期間的裂解價差與 OVX。</li><li>船型、航速、航程與每日耗油量。</li></ul>')}</div></div>${sourceDetails(['依簡報「航運實際成本風險的領先指標」整理。','圖表為指數，不能當作美元價差。','試算公式：每日耗油量 × 天數 × 燃油價格。'])}`}
function fuelGraph(){const series=[[100,102,101,100,99,100,100],[100,103,108,106,113,115,118.6]];const pts=v=>v.map((n,i)=>`${32+i*470/6},${160-(n-90)*4}`).join(' ');return `<svg viewBox="0 0 530 190" role="img" aria-label="原油持平，價差指數升高"><g fill="#8ca2c0" font-size="10">${[90,100,110,120,130].map(n=>`<text x="0" y="${164-(n-90)*4}">${n}</text><path d="M32 ${160-(n-90)*4}H502" stroke="#273b54"/>`).join('')}<text x="32" y="184">期初</text><text x="477" y="184">本期</text></g>${series.map((v,i)=>`<polyline points="${pts(v)}" stroke="${i?'#e4b66c':'#7baaff'}" fill="none" stroke-width="2.5"/>`).join('')}</svg>`}
const PORT_EVENTS=[{area:'南美洲',kind:'港口作業',status:'常態化',title:'阿根廷港口作業延誤',impact:'旺季與勞動因素可能加劇吞吐壓力',route:5},{area:'南美洲',kind:'天災',status:'已發生',title:'巴西洪水與土石流',impact:'內陸公路及鐵路銜接可能中斷',route:5},{area:'南美洲',kind:'治安',status:'已發生',title:'墨西哥治安與道路封鎖',impact:'陸運與港口作業可能受影響',route:3},{area:'歐洲',kind:'施工',status:'前瞻預警',title:'荷蘭鐵路施工',impact:'需查核施工時程及替代內陸運輸',route:0},{area:'歐洲',kind:'天災',status:'已發生',title:'冬季風暴造成交通中斷',impact:'需確認受影響掛靠與交付節點',route:0},{area:'歐洲',kind:'勞動與邊境',status:'常態化',title:'邊境管制與勞動行動',impact:'查核事件範圍與港到門交付影響',route:0}];
function renderPorts(){return `<div class="page-toolbar"><label>區域<select id="portArea"><option>全部</option><option>南美洲</option><option>歐洲</option></select></label><label>事件階段<select id="portStage"><option>全部</option><option>已發生</option><option>常態化</option><option>前瞻預警</option></select></label><span id="portCount" class="toolbar-note"></span></div>${panel('港口與內陸事件','<div id="portTable"></div>','事件追蹤')}<div class="page-grid equal">${panel('事件詳情','<div id="portDetail"><p class="reading">選取事件，查看影響與相關航線。</p></div>')}${panel('監控範圍','<ul class="plain-list"><li>海上抵港之外，也追蹤內陸銜接。</li><li>涵蓋天災、治安、罷工與施工。</li><li>已結束的事件不自動代表影響消失。</li></ul>')}</div>${sourceDetails(['來源：使用者提供的簡報「港口與內陸中斷」。','表格保留簡報的事件分類，不代表目前實際事件狀態。','尚未接入港口公告、事件資料庫或掛靠網路。'])}`}
function updatePorts(){const area=$('#portArea').value,status=$('#portStage').value;const entries=PORT_EVENTS.map((e,i)=>({...e,i})).filter(e=>(area==='全部'||e.area===area)&&(status==='全部'||e.status===status));$('#portCount').textContent=entries.length+' 個事件';$('#portTable').innerHTML=entries.length?table(['事件','區域','類型','階段',''],entries.map(e=>[escapeHTML(e.title),e.area,e.kind,e.status,`<button class="text-button" data-port="${e.i}">查看影響 →</button>`])):emptyData('目前條件沒有對應的事件，請調整篩選。');document.querySelectorAll('[data-port]').forEach(b=>b.onclick=()=>{const e=PORT_EVENTS[+b.dataset.port];$('#portDetail').innerHTML=`<h3>${e.title}</h3><p class="reading">${e.impact}</p>${nextRoute(e.route)}`;bindRouteButtons();});}
const COUNTRY_ROWS=[['智利','DB4a','DB5a','優先進入，長期布局',4,5],['墨西哥','DB4a','DB4c','優先進入，北美延伸',4,4.5],['巴拿馬','DB4a','DB4d','物流樞紐，轉運中心',4,4.75],['秘魯','DB4a','DB5d','選擇性進入，關注 Chancay',4,5.75],['哥倫比亞','DB5','DB5','謹慎評估，限制曝險',5,5],['巴西','DB5a','DB5d','審慎進入，嚴格風控',5,5.75],['阿根廷','DB6a','DB6a','極度限制或避免',6,6]];
function renderCountries(){return `<div class="page-toolbar"><label>查看國家<select id="countrySelect"><option value="all">全部國家</option>${COUNTRY_ROWS.map((c,i)=>`<option value="${i}">${c[0]}</option>`).join('')}</select></label><span class="toolbar-note">CRR 國家風險 · SRR 航運產業風險</span></div><div class="page-grid equal">${panel('國家 × 航運產業風險','<div id="countryChart"></div>','CRR / SRR')}${panel('評級與策略','<div id="countryTable"></div>')}</div>${panel('布局判讀','<p class="reading">國家風險與航運產業風險分開看。結合評級、運量與商業目標，評估市場布局。</p>'+nextRoute(5,'查看南美航線'))}${sourceDetails(['CRR／SRR 與建議策略轉錄自使用者提供的簡報，未取得原始評級報告。','座標採 a＝0、b＝0.25、c＝0.5、d＝0.75，僅供視覺排序，不表示等距風險機率。','圖中虛線為七國樣本平均，並非官方門檻。'])}`}
function updateCountries(){const value=$('#countrySelect').value,rows=value==='all'?COUNTRY_ROWS:[COUNTRY_ROWS[+value]];const x=n=>65+(n-3.5)*130,y=n=>280-(n-3.5)*85;const avgX=COUNTRY_ROWS.reduce((a,c)=>a+c[4],0)/7,avgY=COUNTRY_ROWS.reduce((a,c)=>a+c[5],0)/7;$('#countryChart').innerHTML=`<svg viewBox="0 0 470 330" role="img" aria-label="國家與航運產業風險比較"><g font-size="10" fill="#819aba">${[4,5,6].map(n=>`<path d="M${x(n)} 30V280M65 ${y(n)}H430" stroke="#273b54"/><text x="${x(n)-10}" y="300">DB${n}</text><text x="25" y="${y(n)+3}">DB${n}</text>`).join('')}<text x="20" y="18">SRR ↑</text><text x="370" y="322">CRR →</text></g><path d="M${x(avgX)} 30V280M65 ${y(avgY)}H430" stroke="#7294bb" stroke-dasharray="4 5"/>${COUNTRY_ROWS.map((c,i)=>{const on=value==='all'||+value===i;return `<g opacity="${on?1:.17}"><circle cx="${x(c[4])}" cy="${y(c[5])}" r="5" fill="#78aaff"/><text x="${x(c[4])+9}" y="${y(c[5])+(i===4?15:-7)}" fill="#d2e3fb" font-size="11">${c[0]}</text></g>`}).join('')}</svg>`;$('#countryTable').innerHTML=table(['國家','CRR','SRR','建議策略'],rows.map(c=>c.slice(0,4)));}
function renderRoutes(){return `${panel('航線曝險比較',table(['航線','航道安全','燃油成本','政策與關稅','港口／內陸','國家風險',''],routes.map((r,i)=>[r.name+'<small class="table-sub">'+r.via+'</small>',r.level,'—','—','—','—',`<button class="text-button" data-pick-route="${i}">建立情境 →</button>`])),'五類風險概覽')}<div class="page-grid equal">${panel('情境條件',`<form id="scenarioForm" class="form-grid"><label class="full">分析航線<select name="route" id="scenarioRoute">${routeOptions()}</select></label><label>分析日期<input name="date" type="date" value="2026-10-08" required></label><label>評估目標<select name="goal"><option>兼顧時間與燃油成本</option><option>優先評估時間</option><option>優先評估燃油成本</option></select></label><label>原航程（天）<input name="days" type="number" min="1" max="100" value="28" required></label><label>替代方案增加天數<input name="extra" type="number" min="0" max="60" value="8" required></label><label>每日耗油（噸）<input name="burn" type="number" min="1" max="500" value="70" required></label><label>燃油價格（美元／噸）<input name="price" type="number" min="1" max="5000" value="600" required></label><label class="full">備註<textarea name="note" maxlength="1000" placeholder="例如：到港要求、替代港限制"></textarea></label><button type="submit" class="page-button">計算情境比較</button></form><p class="micro-note">依設定條件比較航程與燃油成本。</p>`) }${panel('方案比較結果','<div id="scenarioResult">'+emptyData('設定條件後計算，查看時間與燃油成本差異。')+'</div>')}</div>`}
function calculateScenario(input){const days=+input.days,extra=+input.extra,burn=+input.burn,price=+input.price;if(![days,extra,burn,price].every(Number.isFinite)||days<1||days>100||extra<0||extra>60||burn<1||burn>500||price<1||price>5000)throw Error('請輸入有效的航程、耗油量與價格。');return {...input,days,extra,burn,price,route:+input.route,baseFuel:days*burn*price,altFuel:(days+extra)*burn*price,altDays:days+extra};}
const money=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
function comparisonHTML(s){return table(['比較項目','原方案','替代情境'],[['航程',s.days+' 天',s.altDays+' 天（+'+s.extra+'）'],['估算燃油成本','USD '+money(s.baseFuel),'USD '+money(s.altFuel)],['燃油成本差額','—','USD +'+money(s.altFuel-s.baseFuel)]]);}
function showScenario(){const s=pageState.scenario;if(!s)return;$('#scenarioResult').innerHTML=`<span class="badge cyan">${escapeHTML(routes[s.route].name)} · ${escapeHTML(s.date)}</span><p class="reading">評估目標：${escapeHTML(s.goal)}</p>${comparisonHTML(s)}<p class="reading">替代情境增加 ${s.extra} 天與 USD ${money(s.altFuel-s.baseFuel)} 燃油成本。</p><button id="toReport" class="page-button">建立分析報告 →</button><button id="locateScenario" class="text-button">在地圖查看航線</button>`;$('#toReport').onclick=()=>navigatePage('reports');$('#locateScenario').onclick=()=>{navigatePage('overview');selectRoute(s.route)};}
function renderReports(){return `<div class="page-grid report-grid">${panel('報告設定',`<form id="reportForm" class="form-grid"><label class="full">報告名稱<input id="reportName" maxlength="100" value="航線情境分析報告" required></label><label class="full">分析航線<select id="reportRoute">${routeOptions()}</select></label><fieldset class="full report-sections"><legend>包含章節</legend><label><input type="checkbox" value="risk" checked>風險摘要</label><label><input type="checkbox" value="comparison" checked>情境比較</label><label><input type="checkbox" value="sources" checked>計算說明</label></fieldset><button type="submit" class="page-button">更新預覽</button><button type="button" id="downloadReport" class="page-button secondary-action">下載 HTML 報告</button></form><p class="micro-note">下載檔案可離線閱讀。只有已完成且航線相符的試算會寫入比較章節。</p>`)}${panel('報告預覽','<article id="reportPreview" class="report-preview"></article>')}</div>${panel('本機匯出紀錄','<div id="reportHistory"></div>','只保存在此瀏覽器')}`}
function makeReport(){const route=+$('#reportRoute').value,r=routes[route],sections=[...document.querySelectorAll('.report-sections input:checked')].map(x=>x.value),s=pageState.scenario?.route===route?pageState.scenario:null;const title=$('#reportName').value.trim()||'航線情境分析報告';let body=`<small>YANG MING · 航運情報</small><h1>${escapeHTML(title)}</h1><h2>${r.name} · ${r.via}</h2><p>產出時間：${new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})}（台北）</p>`;if(sections.includes('risk'))body+=`<section><h2>風險摘要</h2><p>${escapeHTML(routeIssues[route])}</p><p>${escapeHTML(r.note)}</p></section>`;if(sections.includes('comparison'))body+=s?`<section><h2>情境條件與比較</h2><p>分析日期：${escapeHTML(s.date)}；目標：${escapeHTML(s.goal)}</p><p>每日耗油 ${s.burn} 噸，燃油 USD ${s.price}／噸。</p>${comparisonHTML(s)}<p>備註：${escapeHTML(s.note)||'無'}</p></section>`:'<section><h2>情境比較</h2><p>此航線尚未完成試算，未提供比較數值。</p></section>';if(sections.includes('sources'))body+='<section><h2>計算說明</h2><p>試算公式：航程天數 × 每日耗油量 × 燃油價格。未包含港費、租金、保險、碳成本及航速變化。</p></section>';const html=`<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(title)}</title><style>body{font:15px system-ui;line-height:1.9;color:#19314e;max-width:900px;margin:40px auto;padding:24px}h1{font-size:30px}h2{font-size:20px}section{margin:25px 0;border-top:1px solid #d9e1eb;padding-top:15px}.report-warning{padding:15px;background:#fff1dd;border-left:3px solid #d59d48}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #d9e1eb}small{color:#668}@media print{body{margin:0}}</style>${body}</html>`;pageState.report={title,route,html,body};$('#reportPreview').innerHTML=body;}
function reportHistory(){let logs=[];try{logs=JSON.parse(localStorage.getItem('ym-report-history')||'[]');if(!Array.isArray(logs))logs=[];}catch{}$('#reportHistory').innerHTML=logs.length?table(['報告','航線','匯出時間'],logs.map(l=>[escapeHTML(l.title),escapeHTML(l.route),escapeHTML(l.date)])):'<p class="reading">尚無匯出紀錄。下載第一份報告後會出現在這裡。</p>';}
function downloadCurrentReport(){makeReport();const r=pageState.report;const u=URL.createObjectURL(new Blob([r.html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=r.title.replace(/[\\/:*?"<>|]/g,'-')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);try{let logs=JSON.parse(localStorage.getItem('ym-report-history')||'[]');if(!Array.isArray(logs))logs=[];logs.unshift({title:r.title,route:routes[r.route].name,date:new Date().toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})});localStorage.setItem('ym-report-history',JSON.stringify(logs.slice(0,20)));}catch{}reportHistory();}
function bindRouteButtons(){document.querySelectorAll('[data-open-route]').forEach(b=>b.onclick=()=>{pageState.route=+b.dataset.openRoute;navigatePage('routes')});}
function bindPage(page){bindRouteButtons();if(page==='safety'){$('#waterway').onchange=$('#safetyPeriod').onchange=updateSafety;updateSafety();bindRouteButtons();}if(page==='policy'){$('#tradeMarket').onchange=updatePolicy;updatePolicy();}if(page==='fuel'){$('#fuelCalc').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),base=+d.burn*+d.price*+d.days,adjusted=base*(1+(+d.change)/100);$('#fuelResult').innerHTML=`<span>基準燃油成本</span><strong>USD ${money(base)}</strong><span>變動後成本</span><strong>USD ${money(adjusted)}</strong><p>差額：USD ${money(adjusted-base)}</p>`;};}if(page==='ports'){$('#portArea').onchange=$('#portStage').onchange=()=>{updatePorts();$('#portDetail').innerHTML='<p class="reading">選取事件，查看影響與相關航線。</p>';};updatePorts();}if(page==='countries'){$('#countrySelect').onchange=updateCountries;updateCountries();}if(page==='routes'){document.querySelectorAll('[data-pick-route]').forEach(b=>b.onclick=()=>{pageState.route=+b.dataset.pickRoute;$('#scenarioRoute').value=pageState.route;$('#scenarioForm').scrollIntoView({behavior:'smooth',block:'center'});});$('#scenarioForm').onsubmit=e=>{e.preventDefault();const input=Object.fromEntries(new FormData(e.target));pageState.scenario=calculateScenario(input);pageState.route=pageState.scenario.route;showScenario();};if(pageState.scenario){const f=$('#scenarioForm');for(const [k,v] of Object.entries(pageState.scenario)){if(f.elements[k]&&k!=='route')f.elements[k].value=v;}showScenario();}}if(page==='reports'){$('#reportForm').onsubmit=e=>{e.preventDefault();makeReport();};$('#reportRoute').onchange=makeReport;$('#downloadReport').onclick=downloadCurrentReport;makeReport();reportHistory();}}
function renderPage(page){if(!PAGE_MAP[page])page='overview';currentPage=page;document.querySelectorAll('[data-page]').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const home=page==='overview';$('.workspace').hidden=!home;$('#pageContent').hidden=home;document.title=PAGE_MAP[page][0]+' · 陽明航運情報';if(home){requestAnimationFrame(resize);return;}stop();const renders={safety:renderSafety,policy:renderPolicy,fuel:renderFuel,ports:renderPorts,countries:renderCountries,routes:renderRoutes,reports:renderReports};$('#pageContent').innerHTML=`<div class="page-title"><div><span class="page-breadcrumb">陽明航運情報 / ${PAGE_MAP[page][0]}</span><h1>${PAGE_MAP[page][0]}</h1><p>${PAGE_MAP[page][1]}</p></div><a href="#overview" class="text-button">返回總覽 ↗</a></div>${prototypeNote}${renders[page]()}`;$('#pageContent').scrollTop=0;bindPage(page);}
function navigatePage(page){if(location.hash==='#'+page)renderPage(page);else location.hash=page;}
window.addEventListener('hashchange',()=>renderPage(location.hash.slice(1)));
// Existing homepage actions now enter the complete scenario/report workflow.
$('#compare').onclick=()=>{pageState.route=selected;navigatePage('routes')};$('#report2').onclick=$('#reportSelected').onclick=()=>{pageState.route=selected;navigatePage('reports')};$('#export').onclick=()=>{if(currentPage==='overview')pageState.route=selected;navigatePage('reports')};
renderPage(location.hash.slice(1)||'overview');
